### ISSUE TITLE
ergonomics(buttons): tooltip on button icon

### ISSUE THREAD

**Issue by topheman** [system-sdk/system-designer#1]
To know what the buttons really do, you need to click on them - even if they have a shape that can give some insights, the actions they trigger changes between the context they are displayed (system, shema ...).

Simple way would be to add a `title="..."` attribute.

**Comment by ecarriou** [comment]
I added it before with bootstrap tooltip, but I had in issue when using it with electron. I will make another tests and try to put it again in a next release.

**Comment by ecarriou** [comment]
Tooltips are back in System Designer v0.9.0.
