### ISSUE TITLE
Invalid manifest

### ISSUE THREAD

**Issue by charlesprogrammr** [system-sdk/system-designer#2]
I've been getting the following error since last evening.

![image](https://cloud.githubusercontent.com/assets/4869650/15634056/e7d5346e-256f-11e6-956a-1bd7fd433aee.png)

**Comment by charlesprogrammr** [comment]
This is into the new browser, SlimJet, forked from Chrome.

**Comment by ecarriou** [comment]
Thank you for the feedback.
manifest was in fact invalid, I fixed this. Update of the manifest will soon be propagated on Google servers.
